### ISSUE TITLE
MVP mockup

### ISSUE THREAD

**Issue by probablycorey** [cheshire137/gh-notifications-snoozer#1]
_excuse the programmer layout_

![mockup](https://cloud.githubusercontent.com/assets/596/16786715/cf88c110-484b-11e6-94c1-1a72e2a89766.png)

This is really rough. But here are my thoughts...

The "Mentions @github/team-identity-panda-rocket" on the top is where you can view all filters, change the active filter, add new filters, and remove filters. I have no idea how that UI will work.

The filters are limited to "mentions <user/team>" "created by <user>" and "invloves <user>"

The "snooze", "ignore", "archive" items are buttons that will act on the active item, or the checked items below. Just like how mail clients work.

I cut out a bunch or stuff I thought I might want in addition, but I think this will be enough to start a prototype on.

What do you think @cheshire137?

**Comment by cheshire137** [comment]
I like it! When you described it earlier, I had pictured multiple tabs with names like "@github/team-identity-panda-rocket," "Direct mentions," and the like. This looks more focused, like you're only dealing with github/team-identity-panda-rocket issues/PRs right now, which probably fits the actual workflow.

Probably want the repo name included somewhere, since you or a team you're on could be mentioned across multiple repos. Or were you envisioning this view to be repo specific and you'd choose from a list of repos elsewhere? Maybe the list of issues/PRs could be grouped by repo for each filter.

**Comment by probablycorey** [comment]
Here is the latest mockup we worked on together

![img](http://take.ms/JKlTn)
