### ISSUE TITLE
Should we add "user: {user}" to all filters by default?

### ISSUE THREAD

**Issue by summasmiff** [cheshire137/gh-notifications-snoozer#80]
This is a general question about how to prevent confusing behavior for user-generated filters.

Right now, you have to specify `author:{user}`, `commenter:{user}`, etc, etc. to get issues _related to_ the logged in user. If you do not include some `user` field in a filter, you can get anything matching the filter from the entirety of GitHub. 

I feel like this behavior, while sensical from an API standpoint, is likely to confuse people who are used to only using filters from within a repo. 

I have no ideas on what a useful default would be, since there are so many fields `user` could be inserted into. Perhaps if the user is not specified, we tack an `author:{user}` on to the filter? A tooltip / hint to include a user?

**Comment by cheshire137** [comment]
The author and user filters are interesting. For a recent filter that was useful to me, I wanted `-author:cheshire137` but `user:cheshire137` so it would show issues and PRs I didn't create on repos I own. So a combination of user/author is useful.

I think since we start the user off with default filters now, we don't have to set any defaults in the field when the user goes to create a new filter. They've got some existing filters to look at to see what's helpful. If any default, it might be good to put `sort:updated-desc` in the field to start the user off.
