### ISSUE TITLE
Hitting API rate limit

### ISSUE THREAD

**Issue by probablycorey** [cheshire137/gh-notifications-snoozer#95]
I'm hitting the GitHub API limit because of the notification look ups:

![img](https://probablycorey-monosnap.s3.amazonaws.com/Tasks_-_Electron_2016-10-03_14-09-07.png)

**Comment by cheshire137** [comment]
I think instead of automatically fetching all pages of search results, we should fetch just the first and show pagination buttons at the bottom of the tasks list. Then we can load subsequent pages based on user demand.

I think we should continue loading all the pages of notifications, but we should cache the result so we're not continuously refetching them.
